#the title of the gui
title: "<gradient:#00ffa6:#00d1ff><b>Accessories</b></gradient>"

size: 9  #from 9-54

Lang: en_US

Accessory:
  "1":
    lore: ["[Ring]"]
  "3":
    lore: ["[Necklace]"]
  "5":
    lore: ["[Bracelet]"]
  "7":
    lore: ["[Talisman]"]
  #"num":
    #lore: ["[MORE]"]
#As this config it will check weather the item lore has the content like [RING]
frame:
  slots: [0, 2, 4, 6, 8]               #locked slot
  item:
    type: "BLACK_STAINED_GLASS_PANE"
    custom-model-data: 12345
    hide-tooltip: true
    name: "<gray>Locked"
    lore:
      - "<dark_gray>Slot is locked"
Life_Steal_demonstrate: true
OUT_OF_COMBAT_SECONDS: 12
SHIELD_REGEN_PERCENT: 0.10